// Fetches the latest release from the Avark GitHub repo and emits a typed
// module the site imports synchronously. Runs as a `predev` / `prebuild` hook
// so the generated file is always fresh and visitors never hit GitHub at
// runtime (avoids the 60-req/hr unauthenticated rate limit).
//
// Resilient by design: a failed fetch (offline, rate-limited, repo private)
// writes a `null` stub so the build never breaks — the Hero falls back to its
// generic GitHub CTA.
//
// Note: we use the /releases list endpoint (not /releases/latest) because the
// latter skips prereleases, and the current Avark release is a prerelease.

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const OUT = resolve(ROOT, "src/generated/release.ts");

const REPO = process.env.AVARK_REPO ?? "Jeezman/avark";
const API = `https://api.github.com/repos/${REPO}/releases?per_page=10`;

const HEADER = `// AUTO-GENERATED by scripts/fetch-release.mjs — do not edit by hand.
// Regenerated on each \`pnpm dev\` / \`pnpm build\` from the GitHub Releases API.

`;

const TYPE_DECL = `export type ReleaseAsset = {
  name: string;
  browserDownloadUrl: string;
  size: number;
  contentType: string;
};

export type ReleaseInfo = {
  version: string;
  name: string;
  htmlUrl: string;
  publishedAt: string;
  prerelease: boolean;
  assets: ReleaseAsset[];
};

`;

function emit(release) {
  const body = release === null
    ? `export const LATEST_RELEASE: ReleaseInfo | null = null;\n`
    : `export const LATEST_RELEASE: ReleaseInfo | null = ${JSON.stringify(release, null, 2)};\n`;
  return HEADER + TYPE_DECL + body;
}

async function main() {
  await mkdir(dirname(OUT), { recursive: true });

  let release = null;
  try {
    const res = await fetch(API, {
      headers: {
        Accept: "application/vnd.github+json",
        "User-Agent": "avark-landing-build",
      },
    });
    if (!res.ok) {
      throw new Error(`GitHub API ${res.status} ${res.statusText}`);
    }
    const all = await res.json();
    // Skip drafts; keep prereleases. Pick newest by published_at.
    const published = all
      .filter((r) => !r.draft && r.published_at)
      .sort((a, b) => Date.parse(b.published_at) - Date.parse(a.published_at));

    const latest = published[0];
    if (latest) {
      release = {
        version: latest.tag_name,
        name: latest.name ?? latest.tag_name,
        htmlUrl: latest.html_url,
        publishedAt: latest.published_at,
        prerelease: latest.prerelease,
        assets: (latest.assets ?? []).map((a) => ({
          name: a.name,
          browserDownloadUrl: a.browser_download_url,
          size: a.size,
          contentType: a.content_type,
        })),
      };
      console.log(
        `→ release ${release.version} (${release.assets.length} assets) — ${release.htmlUrl}`,
      );
    } else {
      console.log("→ no published releases found; emitting null stub");
    }
  } catch (err) {
    console.warn(`! release fetch failed (${err.message}); emitting null stub`);
  }

  await writeFile(OUT, emit(release));
  console.log(`✓ wrote ${OUT}`);
}

main();
